# Generated by hand to remove District and wire Ward directly to Province
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_district_province_user_address_line_user_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="delivery_addresses",
                to="accounts.province",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="delivery_addresses",
                to="accounts.ward",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ward",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ward",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="wards",
                to="accounts.province",
            ),
        ),
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="district",
        ),
        migrations.RemoveField(
            model_name="user",
            name="district",
        ),
        migrations.RemoveField(
            model_name="ward",
            name="district",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.AlterUniqueTogether(
            name="ward",
            unique_together={("province", "code")},
        ),
    ]

