# Generated by Django 5.2.6 on 2025-11-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_date_of_birth_user_full_name_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['user', 'is_default'], name='accounts_de_user_id_75e2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['user', 'updated_at'], name='accounts_de_user_id_cad4da_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['province', 'ward'], name='accounts_de_provinc_ef79b0_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['province', 'name'], name='accounts_wa_provinc_4179de_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['province', 'code'], name='accounts_wa_provinc_7bd6f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
    ]
