# Generated by Django 5.2.6 on 2025-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="supabase_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
