# Generated by Django 5.2.6 on 2025-11-07 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_drop_savedpaymentmethod_table"),
        ("accounts", "0009_alter_user_supabase_id"),
    ]

    operations = []
