# Generated by Django 5.2.6 on 2025-11-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_merge_20251107_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="supabase_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
