# Generated by Django 5.2.6 on 2025-10-11 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_combo_comboitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="combos",
                to="catalog.category",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
