# Generated by Django 5.2.6 on 2025-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_category_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
