# Generated by Django 5.2.6 on 2025-11-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_combo_stock_menuitem_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name', 'id']},
        ),
    ]
