# Generated by Django 5.2.6 on 2025-11-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options_alter_menuitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='stock',
        ),
    ]
