# Generated by Django 5.2.6 on 2025-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_combo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='combo',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='combo',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
