# Generated by Codex on 2025-XX-XX

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_combo_category_delete_inventory"),
        ("orders", "0002_order_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.combo",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.menuitem",
            ),
        ),
    ]
