# Generated by Django 5.2.6 on 2025-10-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_district_province_user_address_line_user_district_and_more'),
        ('orders', '0003_orderitem_combo_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.deliveryaddress'),
        ),
    ]
