# Generated by Django 5.2.6 on 2025-10-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_fee'),
    ]

    operations = [
    ]
