# Generated by Django 5.2.6 on 2025-10-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20251031_0748'),
    ]

    operations = [
    ]
