# Generated by Django 5.2.6 on 2025-11-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_payment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
