# Generated by Django 5.2.6 on 2025-11-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_payment_completed_at'),
        ('orders', '0013_add_authorized_at'),
    ]

    operations = [
    ]
