# Generated by Django 5.2.6 on 2025-11-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_updated_at'),
        ('orders', '0014_merge_20251106_1429'),
    ]

    operations = [
    ]
