# Generated by Django 5.2.6 on 2025-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_merge_20251106_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authorization_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
