# Generated by Django 5.2.6 on 2025-11-08 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="orders_noti_user_id_7dc029_idx",
            old_name="orders_notif_user_id_idx",
        ),
    ]
