# Generated by Django 5.2.6 on 2025-10-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0002_combo_comboitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="note",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="CartCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("note", models.TextField(blank=True, max_length=500)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combos",
                        to="cart.cart",
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.combo"
                    ),
                ),
            ],
        ),
    ]
