# Generated by Django 5.2.6 on 2025-12-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_note_cartcombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcombo',
            name='combo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
