# Generated by Django 5.2.6 on 2025-11-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Hoàn Kiếm, Hà Nội'", max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('hours', models.CharField(help_text='Operating hours', max_length=200)),
                ('hotline', models.CharField(max_length=50)),
                ('map_query', models.CharField(help_text='Query string for Google Maps embed', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('banner', 'Banner'), ('card', 'Card'), ('text', 'Text'), ('story', 'Story'), ('feature', 'Feature'), ('slide', 'Slide'), ('billboard', 'Billboard')], default='card', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eyebrow', models.CharField(blank=True, help_text='Small tag/label above title', max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional flexible data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='content.page')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
