# Generated by Django 5.2.6 on 2025-11-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slide', 'Slide/Banner'), ('text_block', 'Text Block')], default='card', max_length=50),
        ),
    ]
