# Generated by Django 5.2.6 on 2025-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentitem_description_alter_contentitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('slide', 'Slide/Banner'), ('text_block', 'Text Block'), ('story', 'Story Moment')], default='card', max_length=50),
        ),
    ]
