# Generated by Django 5.2.6 on 2025-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_contentitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
