# Generated by Django 5.2.6 on 2025-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedback_fe_status_212662_idx",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="status",
        ),
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["-created_at"], name="feedback_fe_created_a1f280_idx"
            ),
        ),
    ]
